//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.08.28 at 09:10:17 AM PDT 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://docs.openstack.org/atlas/api/v1.1", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package org.pem.lbaas.datamodel;
