# LBaaS Database schema
# pemellquist@gmail.com

DROP DATABASE IF EXISTS lbaas;
CREATE DATABASE lbaas;
USE lbaas;

# loadbalancers
CREATE TABLE loadbalancers ( 
    id        BIGINT           NOT NULL AUTO_INCREMENT,  # unique id for this loadbalancer, generated by DB when record is created
    name      VARCHAR(50)      NOT NULL,                 # tenant assigned load balancer name
    tenantid  VARCHAR(50)      NOT NULL,                 # tenant id who owns this loadbalancer
    protocol  VARCHAR(50)      NOT NULL,                 # loadbalancer protocol used, can be 'HTTP', 'TCP' or 'HTTPS' 
    port      INT              NOT NULL,                 # TCP port number associated with protocol and used by loadbalancer northbound interface
    status    VARCHAR(50)      NOT NULL,                 # current status, see ATLAS API 1.1 for all possible values
    algorithm VARCHAR(50)      NOT NULL,                 # LB Algorithm in use e.g. ROUND_ROBIN, see ATLAS API 1.1 for all possible values
    vips      VARCHAR(400)     NOT NULL,                 # list of virtual IPs used for this LB (comma and colon separated)
    nodes     VARCHAR(400)     NOT NULL,                 # list of nodes to be LBed accross (comma and colon separated)
    created   VARCHAR(50)      NOT NULL,                 # datestamp of when LB was created
    updated   VARCHAR(50)      NOT NULL,                 # datestamp of when LB was last updated
    device    BIGINT           NOT NULL,                 # reference to associated device OR '0' for unassigned
    PRIMARY KEY (id)                                     # ids are unique accross all LBs
 );

 
 # devices
CREATE TABLE devices ( 
    id           BIGINT      NOT NULL AUTO_INCREMENT,   # unique id for this device, generated by DB when record is created
    name         VARCHAR(50) NOT NULL,                  # admin assigned device name
    address      VARCHAR(50) NOT NULL,                  # IPV4 or IPV6 address of devices mgmt interface
    loadbalancer BIGINT      NOT NULL,                  # Reference to loadbalancer OR '0' for unassigned
    type         VARCHAR(50) NOT NULL,                  # type of device, e.g. 'HAProxy'
    status       VARCHAR(50) NOT NULL,                  # status of device 'OFFLINE', 'ONLINE', 'ERROR'
    PRIMARY KEY (id)
);

 