//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.08.28 at 09:10:17 AM PDT 
//


package org.openstack.docs.atlas.api.v1;

import java.io.Serializable;
import java.util.ArrayList;
import java.util.Calendar;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAnyAttribute;
import javax.xml.bind.annotation.XmlAnyElement;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;
import javax.xml.namespace.QName;
import org.w3._2001.xmlschema.Adapter1;


/**
 * <p>Java class for loadBalancer complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="loadBalancer">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="virtualIps" type="{http://docs.openstack.org/atlas/api/v1.1}virtualIps" minOccurs="0"/>
 *         &lt;element name="nodes" type="{http://docs.openstack.org/atlas/api/v1.1}nodes" minOccurs="0"/>
 *         &lt;element name="healthMonitor" type="{http://docs.openstack.org/atlas/api/v1.1}healthMonitor" minOccurs="0"/>
 *         &lt;element name="sessionPersistence" type="{http://docs.openstack.org/atlas/api/v1.1}sessionPersistence" minOccurs="0"/>
 *         &lt;element name="connectionThrottle" type="{http://docs.openstack.org/atlas/api/v1.1}connectionThrottle" minOccurs="0"/>
 *         &lt;any namespace='##other' maxOccurs="unbounded" minOccurs="0"/>
 *       &lt;/sequence>
 *       &lt;attribute name="id" type="{http://www.w3.org/2001/XMLSchema}int" />
 *       &lt;attribute name="name" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="algorithm" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="protocol" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="port" type="{http://www.w3.org/2001/XMLSchema}int" />
 *       &lt;attribute name="status" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="created" type="{http://www.w3.org/2001/XMLSchema}dateTime" />
 *       &lt;attribute name="updated" type="{http://www.w3.org/2001/XMLSchema}dateTime" />
 *       &lt;anyAttribute namespace='##other'/>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "loadBalancer", propOrder = {
    "virtualIps",
    "nodes",
    "healthMonitor",
    "sessionPersistence",
    "connectionThrottle",
    "anies"
})
@XmlRootElement(name = "loadBalancer")
public class LoadBalancer
    implements Serializable
{

    private final static long serialVersionUID = 532512316L;
    protected VirtualIps virtualIps;
    protected Nodes nodes;
    protected HealthMonitor healthMonitor;
    protected SessionPersistence sessionPersistence;
    protected ConnectionThrottle connectionThrottle;
    @XmlAnyElement(lax = true)
    protected List<Object> anies;
    @XmlAttribute
    protected Integer id;
    @XmlAttribute
    protected String name;
    @XmlAttribute
    protected String algorithm;
    @XmlAttribute
    protected String protocol;
    @XmlAttribute
    protected Integer port;
    @XmlAttribute
    protected String status;
    @XmlAttribute
    @XmlJavaTypeAdapter(Adapter1 .class)
    @XmlSchemaType(name = "dateTime")
    protected Calendar created;
    @XmlAttribute
    @XmlJavaTypeAdapter(Adapter1 .class)
    @XmlSchemaType(name = "dateTime")
    protected Calendar updated;
    @XmlAnyAttribute
    private Map<QName, String> otherAttributes = new HashMap<QName, String>();

    /**
     * Gets the value of the virtualIps property.
     * 
     * @return
     *     possible object is
     *     {@link VirtualIps }
     *     
     */
    public VirtualIps getVirtualIps() {
        return virtualIps;
    }

    /**
     * Sets the value of the virtualIps property.
     * 
     * @param value
     *     allowed object is
     *     {@link VirtualIps }
     *     
     */
    public void setVirtualIps(VirtualIps value) {
        this.virtualIps = value;
    }

    /**
     * Gets the value of the nodes property.
     * 
     * @return
     *     possible object is
     *     {@link Nodes }
     *     
     */
    public Nodes getNodes() {
        return nodes;
    }

    /**
     * Sets the value of the nodes property.
     * 
     * @param value
     *     allowed object is
     *     {@link Nodes }
     *     
     */
    public void setNodes(Nodes value) {
        this.nodes = value;
    }

    /**
     * Gets the value of the healthMonitor property.
     * 
     * @return
     *     possible object is
     *     {@link HealthMonitor }
     *     
     */
    public HealthMonitor getHealthMonitor() {
        return healthMonitor;
    }

    /**
     * Sets the value of the healthMonitor property.
     * 
     * @param value
     *     allowed object is
     *     {@link HealthMonitor }
     *     
     */
    public void setHealthMonitor(HealthMonitor value) {
        this.healthMonitor = value;
    }

    /**
     * Gets the value of the sessionPersistence property.
     * 
     * @return
     *     possible object is
     *     {@link SessionPersistence }
     *     
     */
    public SessionPersistence getSessionPersistence() {
        return sessionPersistence;
    }

    /**
     * Sets the value of the sessionPersistence property.
     * 
     * @param value
     *     allowed object is
     *     {@link SessionPersistence }
     *     
     */
    public void setSessionPersistence(SessionPersistence value) {
        this.sessionPersistence = value;
    }

    /**
     * Gets the value of the connectionThrottle property.
     * 
     * @return
     *     possible object is
     *     {@link ConnectionThrottle }
     *     
     */
    public ConnectionThrottle getConnectionThrottle() {
        return connectionThrottle;
    }

    /**
     * Sets the value of the connectionThrottle property.
     * 
     * @param value
     *     allowed object is
     *     {@link ConnectionThrottle }
     *     
     */
    public void setConnectionThrottle(ConnectionThrottle value) {
        this.connectionThrottle = value;
    }

    /**
     * Gets the value of the anies property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the anies property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getAnies().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Object }
     * 
     * 
     */
    public List<Object> getAnies() {
        if (anies == null) {
            anies = new ArrayList<Object>();
        }
        return this.anies;
    }

    /**
     * Gets the value of the id property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getId() {
        return id;
    }

    /**
     * Sets the value of the id property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setId(Integer value) {
        this.id = value;
    }

    /**
     * Gets the value of the name property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getName() {
        return name;
    }

    /**
     * Sets the value of the name property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setName(String value) {
        this.name = value;
    }

    /**
     * Gets the value of the algorithm property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAlgorithm() {
        return algorithm;
    }

    /**
     * Sets the value of the algorithm property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAlgorithm(String value) {
        this.algorithm = value;
    }

    /**
     * Gets the value of the protocol property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getProtocol() {
        return protocol;
    }

    /**
     * Sets the value of the protocol property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setProtocol(String value) {
        this.protocol = value;
    }

    /**
     * Gets the value of the port property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getPort() {
        return port;
    }

    /**
     * Sets the value of the port property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setPort(Integer value) {
        this.port = value;
    }

    /**
     * Gets the value of the status property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getStatus() {
        return status;
    }

    /**
     * Sets the value of the status property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setStatus(String value) {
        this.status = value;
    }

    /**
     * Gets the value of the created property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public Calendar getCreated() {
        return created;
    }

    /**
     * Sets the value of the created property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCreated(Calendar value) {
        this.created = value;
    }

    /**
     * Gets the value of the updated property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public Calendar getUpdated() {
        return updated;
    }

    /**
     * Sets the value of the updated property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setUpdated(Calendar value) {
        this.updated = value;
    }

    /**
     * Gets a map that contains attributes that aren't bound to any typed property on this class.
     * 
     * <p>
     * the map is keyed by the name of the attribute and 
     * the value is the string value of the attribute.
     * 
     * the map returned by this method is live, and you can add new attribute
     * by updating the map directly. Because of this design, there's no setter.
     * 
     * 
     * @return
     *     always non-null
     */
    public Map<QName, String> getOtherAttributes() {
        return otherAttributes;
    }

}
